// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace csharp_react.Data.Models
{
    public partial class EmployeeHours
    {
        public int ID { get; set; }
        public int EmployeeId { get; set; }
        public DateTime ClockInTime { get; set; }
        public DateTime ClockOutTime { get; set; }

        public virtual Users Employee { get; set; }
    }
}