// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace csharp_react.Data.Models
{
    public partial class Inventory
    {
        public int ItemId { get; set; }
        public string Quantity { get; set; }

        public virtual Items Item { get; set; }
    }
}