// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace csharp_react.Data.Models
{
    public partial class Items
    {
        public Items()
        {
            TransactionPurchases = new HashSet<TransactionPurchases>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string Price { get; set; }

        public virtual ICollection<TransactionPurchases> TransactionPurchases { get; set; }
    }
}