// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace csharp_react.Data.Models
{
    public partial class TransactionPurchases
    {
        public int ID { get; set; }
        public int ItemId { get; set; }
        public int ItemQuantity { get; set; }
        public int TransactionId { get; set; }

        public virtual Items Item { get; set; }
        public virtual Transactions Transaction { get; set; }
    }
}