// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace csharp_react.Data.Models
{
    public partial class Users
    {
        public Users()
        {
            EmployeeHours = new HashSet<EmployeeHours>();
            Transactions = new HashSet<Transactions>();
        }

        public int EmployeeId { get; set; }
        public int Passcode { get; set; }
        public bool IsAdmin { get; set; }

        public virtual ICollection<EmployeeHours> EmployeeHours { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}